apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devopsians
type: Opaque
stringData:
  # MongoDB Atlas connection
  MONGO_URL: "mongodb+srv://mohaamedtariq12_db_user:wuiAicRs8kWVej08@cluster0.pdmzujy.mongodb.net/devopsians?retryWrites=true&w=majority&appName=Cluster0"
  
  # JWT / auth settings
  JWT_SECRET_KEY: "devopsians-super-secret-key"
  JWT_EXPIRE: "1d"
  COOKIE_EXPIRE: "1"
  
  # Production mode
  NODE_ENV: "production"
  
  # Frontend URL with STATIC IP (for CORS and Socket.IO)
  FRONTEND_URL: "https://34.228.5.183"
