apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devopsians
type: Opaque
stringData:
  # TODO: put your real MongoDB Atlas URI here when ready
  MONGO_URL: "mongodb+srv://mohaamedtariq12_db_user:wuiAicRs8kWVej08@cluster0.pdmzujy.mongodb.net/devopsians?retryWrites=true&w=majority&appName=Cluster0"

  # JWT / auth settings â€“ you can change these any time
  JWT_SECRET_KEY: "devopsians-super-secret-key"
  JWT_EXPIRE: "1d"
  COOKIE_EXPIRE: "1"

  # Optional but recommended
  NODE_ENV: "production"

  # Frontend origin used for CORS and Socket.IO
  # Later, set this to your ingress URL, e.g. "http://<elb-dns>"
  FRONTEND_URL: "http://a90948608251e497faf8043960578813-903063d412e53431.elb.us-east-1.amazonaws.com"