apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsians-ingress
  namespace: devopsians
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Frontend SPA + assets
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # Backend HTTP API Routes
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /manager
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /receptionist
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /patient
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /ambulance
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /icu
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /hospital
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030
                  
          - path: /meta
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030

          # Socket.IO endpoint (client is already using /socket.io)
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3030

